// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TokoBuku.Models;

namespace TokoBuku.Migrations
{
    [DbContext(typeof(BukuContext))]
    partial class BukuContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TokoBuku.Models.rakbuku", b =>
                {
                    b.Property<int>("id_buku")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("diskon")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("gambar_buku")
                        .HasColumnType("varchar(120)");

                    b.Property<int>("harga")
                        .HasColumnType("int");

                    b.Property<int>("jumlah_buku")
                        .HasColumnType("int");

                    b.Property<string>("kategori_buku")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("nama_buku")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("penerbit_buku")
                        .HasColumnType("varchar(80)");

                    b.HasKey("id_buku");

                    b.ToTable("rakbuku");
                });
#pragma warning restore 612, 618
        }
    }
}
